-- GreptimeDB retention / TTL.
--
-- Retention is database-level and applied programmatically, not from this file. The schema
-- bootstrap (`applyGreptimeMigrations`, run via `pnpm --filter=@langfuse/shared run greptime:migrate`)
-- emits an idempotent `ALTER DATABASE <db> SET 'ttl'='<duration>'` after the schema is in place.
-- The duration comes from LANGFUSE_GREPTIME_TTL (default 730d / 2 years). A single database TTL
-- applies to every table — raw_events, the projection snapshots, and the EAV tables — so the whole
-- store shares one expiry horizon.
--
-- Change retention for everything at once, at any time:
--   ALTER DATABASE openfuse SET 'ttl'='365d';   -- or clear with SET 'ttl'=NULL
--
-- One shared horizon keeps the projection-rebuild contract simple: each projection snapshot is
-- rebuilt by replaying the entity's raw_events history, and with raw_events and projections
-- expiring at the same age a projection does not outlive raw_events written at the same time.
-- GreptimeDB measures TTL per row from the row timestamp, so a raw `create` event written earlier
-- than the entity's latest projection update can expire slightly sooner; operators who need a
-- strict raw_events >= projection margin can override raw_events with a longer table-level TTL,
-- which takes precedence over the database TTL:
--   ALTER TABLE raw_events SET 'ttl'='1095d';
--
-- (deletion.ts still hard-deletes projection + EAV rows for EXPLICIT project / entity deletion;
-- that is a separate concern from time-based retention and is not driven from here.)
--
-- This file intentionally contains no executable statements; the database TTL is applied by the
-- bootstrap step described above.
