-- GreptimeDB retention / TTL (02-write-path.md, invariant 6).
--
-- OPTIONAL, OPT-IN. The base schema (0001_init.sql) sets no TTL, so a fresh install keeps data
-- forever and projection rebuilds are always complete. A self-hosted operator who wants to cap
-- disk usage can enable a GLOBAL table-level TTL here (GreptimeDB has no per-project / per-row TTL).
--
-- Prefer the helper over editing this file: set LANGFUSE_GREPTIME_RAW_EVENTS_TTL +
-- LANGFUSE_GREPTIME_PROJECTION_TTL and run `applyGreptimeRetention`
-- (packages/shared/src/server/greptime/retention.ts), which validates invariant 6 before applying.
-- The statements below mirror what that helper emits, for manual / out-of-band application.
--
-- INVARIANT 6 (hard): raw_events TTL MUST be >= the projection TTL. The worker rebuilds each
-- projection snapshot by replaying the entity's FULL raw_events history; if a `create` event
-- expires from raw_events while its projection survives, the rebuild loses immutable fields /
-- metadata / tags and silently corrupts the projection. raw_events is append-only (no DELETE), so
-- it relies solely on this TTL — size it from the maximum entity-update / reprocess window, not as
-- a cost knob. (deletion.ts still hard-deletes projection + EAV rows for EXPLICIT project / entity
-- deletion; that is a separate concern from time-based retention and is not driven from here.)
--
-- Syntax (GreptimeDB 1.x): `ALTER TABLE t SET 'ttl'='<duration>'`; clear with `SET 'ttl'=NULL`.
-- Apply: mysql -h127.0.0.1 -P4002 -uroot openfuse < 0002_retention.sql

-- Backstop: keep raw_events (source of truth) at least as long as any projection horizon.
-- ALTER TABLE raw_events SET 'ttl'='400d';

-- Projection + EAV retention (each MUST be <= the raw_events TTL above).
-- ALTER TABLE traces                SET 'ttl'='365d';
-- ALTER TABLE observations          SET 'ttl'='365d';
-- ALTER TABLE scores                SET 'ttl'='365d';
-- ALTER TABLE traces_metadata       SET 'ttl'='365d';
-- ALTER TABLE observations_metadata SET 'ttl'='365d';
-- ALTER TABLE scores_metadata       SET 'ttl'='365d';
-- ALTER TABLE traces_tags           SET 'ttl'='365d';
-- ALTER TABLE observations_tags     SET 'ttl'='365d';
-- ALTER TABLE scores_tags           SET 'ttl'='365d';
